### ISSUE TITLE
Any performance comparison?

### ISSUE THREAD

**Issue by trusktr** [matthewp/fritz#21]
It would be neat to see a non-worker example compared to a worker example.

**Comment by matthewp** [comment]
Hey, sorry for the late reply. Not yet, I've been working on improving perf in this branch https://github.com/matthewp/fritz/tree/my-diff. Currently it is middle of the road compared to other vdom libraries, but I haven't attempted to improve perf at all until now. We'll see how it goes.

Absolute performance is not the point of fritz. The point is to ensure that you never block the main thread for the bulk of your application. The performance sensitive things like animations can and should be written as window-side components.

**Comment by snuggs** [comment]
@trusktr it's "fast enough". The benchmark of benchmarks 🍻  /cc @matthewp

**Comment by matthewp** [comment]
@snuggs Don't be an asshole.

**Comment by snuggs** [comment]
Yet i just heard from a JS benchmark talk from ember guys "fast enough is usually fast enough". hence the quotes. Possibly [Poe's law](https://en.wikipedia.org/wiki/Poe%27s_law). But you're reaching cursing me out @matthewp.  I actually enjoyed your library and spoke on it here in NYC. Please don't curse people out and be a bully to people who actually recommend your warez without assessing tone first.

I actually cannot see it in my blood disrespecting @trusktr. Guy's been skating as long as i have.

Peace :peace_symbol:

**Comment by matthewp** [comment]
My apologies, I misinterpreted your post @snuggs.

Given the trade off of developing off thread I don't think fast enough will fly here. Hence why I'm putting some work in (slowly) to make it faster.

**Comment by snuggs** [comment]
No worries at all man! In OSS gots to keep your guard up sometimes these days unfortunately. For the curmudgeons. Sad but true #Metallica :metal:

Ironically it was because someone asked me how fast Fritz was and i didn't know the answer. I said "Well 'instant' is 30ms and it's not creating jank so it's fast enough". But to your point that's the purpose of this library. Looking forward to the tests! And enjoy your day sir!

**Comment by matthewp** [comment]
Well, working on this library again. And came across this again. My apologies again @snuggs, what a regrettable thing that I said. Appreciate your forgiveness.

Going to close this thread, I do plan on adding a lot of performance content to the documentation, but it won't come in the form of direct comparison.
